// Database types generated by Prisma from the schema.
// Import from @prisma/client for full type safety.
//
// To regenerate after schema changes:
//   DIRECT_URL='...' npx prisma generate
//
// To generate Supabase-native types (for RLS-aware client queries):
//   npx supabase login
//   npx supabase gen types typescript --project-id dgsbtyvbmkxcthrkucqc > lib/supabase/types.ts

export type {
  User,
  Listing,
  ListingMedia,
  FinancialSubmission,
  FinancialLine,
  EbitdaAddback,
  StandardizedFinancial,
  ValuationRun,
  ValuationInquiry,
  IndustryTaxonomy,
  IndustryBenchmark,
  ComparableTransaction,
  DataSource,
  IndustryMetricTemplate,
  SubmissionMetric,
  Document,
  DocumentAccessLog,
  AccessGrant,
  MessageThread,
  Message,
  MessageAttachment,
  NdaSignature,
  LegalDocument,
  Offer,
  DueDiligenceChecklist,
  SavedListing,
  SavedSearch,
  Notification,
  AuditLog,
  ListingView,
  AnalyticsEvent,
  ReviewQueue,
  Payment,
  SubscriptionPlan,
  Subscription,
  ExternalCustomer,
  DataExport,
  DataExportRecord,
  AccountStatusHistory,
  RetentionPolicy,
  DeletionRequest,
} from "@prisma/client";
